# Generated by Django 2.1.5 on 2019-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Magazada', 'Magazada'), ('Catdirilma', 'Catdirilma')], default='Magazada', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Qeyde alindi', 'Qeyde alindi'), ('Icra olunur', 'Icra olunur'), ('Odenilib', 'Odenilib')], default='Qeyde alindi', max_length=100),
        ),
    ]
