# Generated by Django 2.2.10 on 2020-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
    ]
