# Generated by Django 2.2.10 on 2020-07-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200704_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.MainCategory'),
        ),
    ]
