# Generated by Django 3.0.4 on 2020-03-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_multiimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product'),
        ),
    ]
