# Generated by Django 2.2.10 on 2020-07-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200705_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='catalog.SubCategory', verbose_name='Kategoriya'),
        ),
    ]
