# Generated by Django 2.2 on 2020-08-19 14:49

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200819_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='products',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='catalog.Product'),
        ),
    ]
