# Generated by Django 2.2.10 on 2020-07-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200705_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypromocode',
            name='products',
        ),
    ]
