# Generated by Django 3.0.4 on 2020-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200319_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fovarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('product', models.ManyToManyField(to='catalog.Product')),
            ],
        ),
    ]
