# Generated by Django 2.2.10 on 2020-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_companypromocode_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypromocode',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Promocoddan istifade olunub'),
        ),
    ]
