# Generated by Django 2.2.10 on 2020-05-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200520_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
