# Generated by Django 2.2 on 2020-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200819_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
    ]
