# Generated by Django 3.0.4 on 2020-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_fovarite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fovarite',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
