# Generated by Django 2.2.10 on 2020-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200707_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypromocode',
            name='money',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manat'),
        ),
    ]
