# Generated by Django 2.2 on 2020-08-19 14:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200819_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
