# Generated by Django 3.0.4 on 2020-03-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200319_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fovarite',
            old_name='product',
            new_name='products',
        ),
    ]
