# Generated by Django 2.2.10 on 2020-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_companypromocode_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypromocode',
            name='faiz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Endirim Faiz Derecesi'),
        ),
    ]
