# Generated by Django 3.0.4 on 2020-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200319_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fovarite',
            name='products',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
    ]
