# Generated by Django 2.2 on 2020-08-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200820_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='pr', to='catalog.Product'),
        ),
    ]
