# Generated by Django 3.0.4 on 2020-03-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200319_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='fovarite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fovarite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Fovarite',
        ),
    ]
