# Generated by Django 2.2 on 2020-09-10 06:52
from django.contrib.postgres.operations import UnaccentExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200820_2127'),
    ]

    operations = [
        UnaccentExtension()
    ]
