# Generated by Django 2.2.10 on 2020-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200520_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month_18',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 12 ay ucun ayliq odenis'),
        ),
    ]
