# Generated by Django 2.2.10 on 2020-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_month_18'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to='date',
        ),
    ]
