# Generated by Django 3.0.4 on 2020-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_fovarite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fovarite',
            name='fovarites',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='fovarite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fovarite',
        ),
        migrations.AddField(
            model_name='fovarite',
            name='fovarit',
            field=models.ManyToManyField(blank=True, to='catalog.Product'),
        ),
    ]
