# Generated by Django 2.2.10 on 2020-05-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200521_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='comment',
            order_with_respect_to=None,
        ),
    ]
