# Generated by Django 3.0.4 on 2020-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_fovarite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fovarite',
            name='fovarit',
            field=models.ManyToManyField(blank=True, related_name='fovar', to='catalog.Product'),
        ),
    ]
