# Generated by Django 2.2.4 on 2020-08-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200729_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mehsulun categoriyasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Yekun Qiymeti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Kredit 12 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Kredit 15 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_18',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Kredit 18 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Kredit 6 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='month_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Kredit 9 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Qiymeti'),
        ),
    ]
