# Generated by Django 3.0 on 2020-04-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200319_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
