# Generated by Django 2.2.4 on 2020-08-01 05:31

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200801_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
