# Generated by Django 2.2.10 on 2020-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_main_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, verbose_name='Yekun Qiymeti'),
        ),
    ]
