# Generated by Django 2.2.10 on 2020-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200801_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mehsulun Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Yekun Qiymeti'),
        ),
    ]
