# Generated by Django 2.2.10 on 2020-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200801_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Yekun Qiymeti'),
        ),
    ]
