# Generated by Django 2.1.5 on 2020-04-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200414_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Kodun Faiz Derecesi')),
                ('code', models.CharField(max_length=300, verbose_name='Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo_kod',
        ),
        migrations.AddField(
            model_name='promocode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='catalog.Product'),
        ),
    ]
