# Generated by Django 2.1.5 on 2020-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200416_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.IntegerField(verbose_name='Kodun Faiz Derecesi'),
        ),
    ]
