# Generated by Django 2.2.10 on 2020-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200601_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='month_18',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.IntegerField(blank=True, null=True, verbose_name='Promocodun Faiz Derecesi'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Olculer'),
        ),
        migrations.DeleteModel(
            name='Kredit_18_ay',
        ),
    ]
