# Generated by Django 2.1.5 on 2020-04-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200416_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Kampaniya Adi')),
                ('faiz', models.IntegerField(verbose_name='Endirim Faiz Derecesi')),
                ('products', models.ManyToManyField(to='catalog.Product', verbose_name='Mehsullar')),
            ],
        ),
    ]
