# Generated by Django 2.2.10 on 2020-08-17 08:18

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='products',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='catalog.Product'),
        ),
    ]
