# Generated by Django 2.1.5 on 2020-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_companypromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypromocode',
            name='code',
            field=models.CharField(default=1, max_length=300, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
