# Generated by Django 2.2.10 on 2020-06-01 20:47

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200601_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=colorful.fields.RGBColorField(),
        ),
    ]
