# Generated by Django 2.1.5 on 2020-04-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_companypromocode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kredit_18_ay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faiz', models.IntegerField(blank=True, verbose_name='18 Ay ucun faiz derecesi')),
                ('odenis', models.CharField(blank=True, max_length=100, verbose_name='Ayliq odenis')),
            ],
        ),
        migrations.AddField(
            model_name='companypromocode',
            name='count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Promocoddan istifade olunub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypromocode',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='Maksimum istifade Dayi - Limit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='month_12',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 12 ay ucun ayliq odenis'),
        ),
        migrations.AddField(
            model_name='product',
            name='month_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 6 ay ucun ayliq odenis'),
        ),
        migrations.AlterField(
            model_name='companypromocode',
            name='products',
            field=models.ManyToManyField(related_name='company', to='catalog.Product', verbose_name='Mehsullar'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=300, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.IntegerField(verbose_name='Promocodun Faiz Derecesi'),
        ),
        migrations.AddField(
            model_name='kredit_18_ay',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kredit', to='catalog.Product'),
        ),
    ]
