# Generated by Django 2.2.10 on 2020-06-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200601_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_code',
            new_name='color',
        ),
    ]
