# Generated by Django 2.2.10 on 2020-06-01 21:09

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200601_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
