# Generated by Django 2.2.10 on 2020-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200602_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month_15',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 15 ay ucun ayliq odenis'),
        ),
        migrations.AddField(
            model_name='product',
            name='month_18',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 18 ay ucun ayliq odenis'),
        ),
        migrations.AddField(
            model_name='product',
            name='month_9',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kredit 9 ay ucun ayliq odenis'),
        ),
    ]
