# Generated by Django 2.2.10 on 2020-06-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20200602_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='month_6',
        ),
    ]
