# Generated by Django 2.2.10 on 2020-06-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20200602_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='month_12',
        ),
        migrations.RemoveField(
            model_name='product',
            name='month_15',
        ),
        migrations.RemoveField(
            model_name='product',
            name='month_18',
        ),
        migrations.RemoveField(
            model_name='product',
            name='month_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='month_9',
        ),
    ]
