# Generated by Django 2.2.10 on 2020-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=1, max_length=100, verbose_name='Bar kod'),
            preserve_default=False,
        ),
    ]
